services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3005:3005'
    env_file:
      - .env
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - clamav

  clamav:
    image: clamav/clamav:latest
    volumes:
      - clamav_data:/var/lib/clamav
    ports:
      - '3310:3310'
    environment:
      - CLAMAV_NO_FRESHCLAM=false
      - FRESHCLAM_CHECKS=24

volumes:
  clamav_data: